### PR TITLE
Icons theme name

### PR DESCRIPTION
**Pull request by Arnaudv6**
Hello Papy, nice screenshot!

### CODE REVIEW

**Comment by PapyElGringo** [comment]
Hello Arnaud, thanks !

The icon theme for GTK is Papirus-Dark if it's your question

**Comment by PapyElGringo** [comment]
But not sure why we got a PR here hehe

**Comment by Arnaudv6** [comment]
Hello Papy, thanks for your kind answer: this indeed answers my question.  
The pull request was just about suggesting you updating the description in the read-me; so I am the last one bothering you hopefully.

**Comment by PapyElGringo** [comment]
Ok thanks it's just that the GTK stuff theme and icons are more related to my config than to the Material-Awesome project. But Im gonna improve the readme soon anyway!

Thanks

**Pull request closed without merging**
